[build]
  # 构建命令
  command = "npm run build"
  # 发布目录
  publish = "dist"
  # 函数目录（用于Netlify Functions）
  functions = "netlify/functions"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"
  # 生产环境
  NODE_ENV = "production"

# 重定向规则 - 处理 React Router
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 开发设置
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 3001
  autoLaunch = false

# 插件配置
[[plugins]]
  package = "@netlify/plugin-functions-install-core"